---
- name: Update rc files
  hosts: localhost
  tasks:
  - name: Get the target username
    become: false
    command: whoami
    register: target_username
  - debug:
      msg: "Making changes for {{ target_username.stdout | default('me') }}"
  - name: Create directories
    file:
      path: "{{ item }}"
      state: directory
      mode: '0700'
    with_items:
      - ~/.scripts
      - ~/.scripts/env
  - name: Copy main rc file
    template:
      src: files/rc.j2.sh
      dest: ~/.scripts/rc
      mode: '0755'
  - name: Include all modules
    include_tasks: tasks/{{ item }}.yml
    loop: "{{ modules_to_manage }}"
    ignore_errors: yes
  - name: Copy env file
    include_tasks: tasks/_copy_env_file.yml
    loop: "{{ modules_to_manage }}"
    vars:
      name: "{{ item }}"
  - name: Plug rc in *rc
    lineinfile:
      path: ~/.{{ item }}
      line: "source ~/.scripts/rc"
    with_items:
      - bashrc
      - zshrc
