---
- name: Update rc files
  hosts: localhost
  tasks:
  - name: Get the target username
    become: false
    command: whoami
    register: target_username
  - debug:
      msg: "Making changes for {{ target_username.stdout | default('me') }}"
  - name: Create directories
    file:
      path: "{{ dir_to_create }}"
      state: directory
      mode: '0700'
    loop:
      - ~/.scripts
      - ~/.scripts/env
    loop_control:
      loop_var: dir_to_create
  - name: Populate main rc file
    lineinfile:
      path: ~/.scripts/rc
      line: "{{ line_to_add }}"
      insertafter: EOF
      create: yes
    loop:
      - export EDITOR=vim
      - export PATH=$PATH:~/.scripts
    loop_control:
      loop_var: line_to_add
  - name: Include all modules
    include_tasks: tasks/{{ item }}.yml
    loop: "{{ modules_to_manage }}"
    ignore_errors: yes
  - name: Plug rc in *rc
    lineinfile:
      path: ~/.{{ shells }}
      line: "source ~/.scripts/rc"
    loop:
      - bashrc
      - zshrc
    loop_control:
      loop_var: shells
