---
- name: Copy env file
  include_tasks: tasks/_copy_env_file.yml
  vars:
    name: "docker"
- name: Install docker
  become: yes
  pacman:
    name: 
      - docker
      - docker-compose
      - python-docker
      - python-dockerpty
      - python-docker-pycreds
- name: Enable start docker
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes
- name: Add current user to docker group
  become: yes
  user:
    name: "{{ target_username.stdout | default('me') }}"
    groups:
      - docker
    append: yes
