---
- name: Install docker
  become: yes
  pacman:
    name: 
      - docker
      - docker-compose
      - python-docker
      - python-dockerpty
      - python-docker-pycreds
- name: Enable start docker
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes
- name: Add current user to docker group
  become: yes
  user:
    name: "{{ target_username.stdout }}"
    groups:
      - docker
    append: yes
