---
- name: Copy env file
  include_tasks: tasks/_copy_env_file.yml
  vars:
    name: "go"
- name: Install go
  become: yes
  pacman:
    name: 
      - go
- name: Install go tools
  shell: go get {{ item }}
  with_items:
    - golang.org/x/tools/cmd/goimports
