---
- name: Copy env file
  include_tasks: tasks/_copy_env_file.yml
  vars:
    name: "kubernetes"
- name: Install kubernetes utilities
  become: yes
  pacman:
    name: 
      - kubectl
      - kubectx
- name: Install kubernetes utilities cont'd
  command: pamac install --no-confirm kubeval
