---
- name: Copy env file
  include_tasks: tasks/_copy_env_file.yml
  vars:
    name: "podman"
- name: Disable stop docker
  become: yes
  systemd:
    name: docker
    state: stopped
    enabled: no
  ignore_errors: yes
- name: Remove docker
  become: yes
  pacman:
    state: absent
    name: 
      - docker

- name: Install podman
  become: yes
  pacman:
    name:
      - podman
      - slirp4netns
      - docker-compose
      - python-docker
      - python-dockerpty
      - python-docker-pycreds
- name: Create subuid and subgid files for rootless podman
  become: yes
  file:
    path: "{{ item }}"
    state: touch
  loop:
    - /etc/subuid
    - /etc/subgid
- name: Configure rootless podman
  become: yes
  command: usermod --add-subuids 200000-201000 --add-subgids 200000-201000 "{{ target_username.stdout | default('me') }}"
- name: Enable start podman socket
  become: yes
  systemd:
    name: podman.socket
    state: started
    enabled: yes
- name: Configure default registry
  become: yes
  lineinfile:
    create: yes
    path: /etc/containers/registries.conf.d/00-default-docker-hub
    line: unqualified-search-registries = ["docker.io"]
