---
- name: Copy env file
  include_tasks: tasks/_copy_env_file.yml
  vars:
    name: "zoxide"
- name: Install zoxide & fzf
  become: yes
  pacman:
    name: 
      - fzf
- name: Install zoxide & fzf cont'd
  command: pamac install --no-confirm zoxide
