---
- name: Install zsh
  become: yes
  pacman:
    name: 
      - zsh
      - oh-my-zsh
- name: Copy rc file
  copy:
    src: files/rc.zsh.sh
    dest: ~/.scripts/zshrc
- name: Plug rc file
  lineinfile:
    path: ~/.zshrc
    line: "source ~/.scripts/zshrc"
    insertbefore: BOF
    create: yes
- name: Set zsh the default shell
  become: yes
  user:
    name: "{{ target_username.stdout }}"
    shell: /usr/bin/zsh
